language: android
android:
  components:
  - build-tools-19.1.0
  - android-19
script: ./gradlew clean assembleRelease deployLocal
after_success:
    - pwd
    - ls
    - ls app/build/outputs/apk
    - ls headlessplayertest_builds/master
deploy:
  provider: gcs
  access_key_id: GOOGTYSCNGUSQPKIOB6N
  secret_access_key:
    secure: tx1+kBFEagY2iWKSOy9uSz71vbwwr9EVuyLF5B9AJTxbalSyp69xRRQa4meUrIffYUeAsZvf9WDfBxjRpYEqi6TPhb5uQstQCg6Aji05sYzvgZySwzt+pWKcK9JdfOf7aeLKPlWSf3e8x26wDjCriI8dufNp52y+MsjUm5ZD7PU=
  bucket: headlessplayertest_builds
  skip_cleanup: true
  local-dir: headlessplayertest_builds/master
  upload-dir: master
  on:
    all_branches: true
